# Generated by Django 5.1.4 on 2025-01-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0005_alter_sitesetup_favicon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetup',
            name='show_seach',
        ),
        migrations.AddField(
            model_name='sitesetup',
            name='show_search',
            field=models.BooleanField(default=True),
        ),
    ]
